### ISSUE TITLE
if username does not exists in the db, then UI should show the message

### ISSUE THREAD

**Issue by xiaofengli** [xiaofengli/mockingtest3#63]
If db does not have an user, and if we enter the user name and password, and we will get the follow exception.

Caused by: java.lang.NullPointerException: null
	at com.mocking.service.UserDetailsServiceImpl.loadUserByUsername(UserDetailsServiceImpl.java:31) ~[classes/:na]
	at com.mocking.service.UserDetailsServiceImpl$$FastClassBySpringCGLIB$$c9addd1a.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.3.RELEASE.jar:5.1.3.RELEASE

**Comment by xiaofengli** [comment]
Please register an user, login with it successfully. Then delete it from the db, and then handle this exception.
